- name: Enable service rngd
  block:

    - name: Gather the package facts
      package_facts:
        manager: auto

    - name: Enable service rngd
      service:
        name: rngd
        enabled: 'yes'
        state: started
        masked: 'no'
      when:
        - '"rng-tools" in ansible_facts.packages'
  when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]
  tags:
    - CCE-82831-9
    - DISA-STIG-RHEL-08-010471
    - enable_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - service_rngd_enabled